services:
  database:
    image: postgres:17.4
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./django_dog_info:/django_dog_info
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASSWORD=dbpass
    depends_on:
      - database

volumes:
  postgres_data:
